/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const MadiverifyLazyImport = createFileRoute('/madi_verify')()
const LicenseformLazyImport = createFileRoute('/license_form')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const MadiverifyLazyRoute = MadiverifyLazyImport.update({
  path: '/madi_verify',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/madi_verify.lazy').then((d) => d.Route))

const LicenseformLazyRoute = LicenseformLazyImport.update({
  path: '/license_form',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/license_form.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/license_form': {
      preLoaderRoute: typeof LicenseformLazyImport
      parentRoute: typeof rootRoute
    }
    '/madi_verify': {
      preLoaderRoute: typeof MadiverifyLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  LicenseformLazyRoute,
  MadiverifyLazyRoute,
])

/* prettier-ignore-end */
